version: '3' #Version Docker COmpose

services:

  # 1. Container Tweet_Collector
  tweet_collector:
    container_name: tweet_collector
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on: 
      - mongodb
    environment: 
      - TW_API_KEY=${TW_API_KEY}
      - TW_API_SECRET=${TW_API_SECRET}
      - TW_ACC_TOKEN=${TW_ACC_TOKEN}
      - TW_ACC_SECRET=${TW_ACC_SECRET}

  # 2. Container MongoDB
  mongodb:
    container_name: mongo
    image: mongo # mongo image from Docker-Hub
    ports: # port connection on_local_machine:inside_of_container
    - 27018:27017

  # 3. Container ETL
  etl_job:
    container_name: etl_job
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on: #lit à partir de mongodb et écrit dans postgres, donc on a besoin des 2
    - mongodb
    - postgresdb
    restart: on-failure
    environment: # keys declarés dans env_vars 
    - POSTGRES_USER=${TW_PG_USER}
    - POSTGRES_PASSWORD=${TW_PG_PASS}
    - POSTGRES_DB=${TW_PG_DBNAME}
  

  # 4. Container Postgres
  postgresdb:
    container_name: postgres
    image: postgres 
    ports: # on_local_machine:inside_of_container
    - "5555:5432"
    environment: # env_vars
    - POSTGRES_USER=${TW_PG_USER}
    - POSTGRES_PASSWORD=${TW_PG_PASS}
    - POSTGRES_DB=${TW_PG_DBNAME}


  # 5. Container Discord
  discordbot:
    container_name: discordbot
    build: discordbot/
    volumes:
    - ./discordbot/:/app
    depends_on: # This reads from postgres thus requires postgres to run, mangodb dont need to run on this case
    - postgresdb
    restart: on-failure
    environment: 
    - POSTGRES_USER=${TW_PG_USER}
    - POSTGRES_PASSWORD=${TW_PG_PASS}
    - POSTGRES_DB=${TW_PG_DBNAME}
    - WEBHOOK=${TT_ DISCORD_WEBHOOK}
